/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Dummy } from '../../models/dummy';

export interface DummyLogicPost$Params {
      body: Dummy
}

export function dummyLogicPost(http: HttpClient, rootUrl: string, params: DummyLogicPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Dummy>> {
  const rb = new RequestBuilder(rootUrl, dummyLogicPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Dummy>;
    })
  );
}

dummyLogicPost.PATH = '/dummy-logic';
