/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Dummy } from '../../models/dummy';

export interface DummiesGet$Params {
}

export function dummiesGet(http: HttpClient, rootUrl: string, params?: DummiesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Dummy>>> {
  const rb = new RequestBuilder(rootUrl, dummiesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Dummy>>;
    })
  );
}

dummiesGet.PATH = '/dummies';
