/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiPingGet$Params as ApiPingGet$Params } from './fn/web-api/api-ping-get';
export { apiPingGet as apiPingGet } from './fn/web-api/api-ping-get';
export type { ApiOrdersGet$Params as ApiOrdersGet$Params } from './fn/web-api/api-orders-get';
export { apiOrdersGet as apiOrdersGet } from './fn/web-api/api-orders-get';
export type { ApiOrdersPost$Params as ApiOrdersPost$Params } from './fn/web-api/api-orders-post';
export { apiOrdersPost as apiOrdersPost } from './fn/web-api/api-orders-post';
export type { ApiOrdersIdGet$Params as ApiOrdersIdGet$Params } from './fn/web-api/api-orders-id-get';
export { apiOrdersIdGet as apiOrdersIdGet } from './fn/web-api/api-orders-id-get';
export type { ApiValidateBraceletPost$Params as ApiValidateBraceletPost$Params } from './fn/web-api/api-validate-bracelet-post';
export { apiValidateBraceletPost as apiValidateBraceletPost } from './fn/web-api/api-validate-bracelet-post';
