// <auto-generated />
using System;
using AppServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppServices.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AppServices.Laufbewerb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("LaufkategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Streckenlänge")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LaufkategorieId");

                    b.ToTable("Laufbewerbe");
                });

            modelBuilder.Entity("AppServices.Laufkategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Laufkategorien");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bezeichnung = "Straßenlauf"
                        },
                        new
                        {
                            Id = 2,
                            Bezeichnung = "Crosslauf"
                        },
                        new
                        {
                            Id = 3,
                            Bezeichnung = "Bahnlauf"
                        },
                        new
                        {
                            Id = 4,
                            Bezeichnung = "Trailrun"
                        });
                });

            modelBuilder.Entity("AppServices.Split", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KmNummer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SegmentLaenge")
                        .HasColumnType("REAL");

                    b.Property<int>("TeilnehmerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZeitSekunden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeilnehmerId");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("AppServices.Teilnehmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AngestrebteGesamtzeit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaufbewerbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Startnummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LaufbewerbId");

                    b.ToTable("Teilnehmer");
                });

            modelBuilder.Entity("AppServices.Laufbewerb", b =>
                {
                    b.HasOne("AppServices.Laufkategorie", "Laufkategorie")
                        .WithMany()
                        .HasForeignKey("LaufkategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Laufkategorie");
                });

            modelBuilder.Entity("AppServices.Split", b =>
                {
                    b.HasOne("AppServices.Teilnehmer", "Teilnehmer")
                        .WithMany("Splits")
                        .HasForeignKey("TeilnehmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teilnehmer");
                });

            modelBuilder.Entity("AppServices.Teilnehmer", b =>
                {
                    b.HasOne("AppServices.Laufbewerb", "Laufbewerb")
                        .WithMany()
                        .HasForeignKey("LaufbewerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laufbewerb");
                });

            modelBuilder.Entity("AppServices.Teilnehmer", b =>
                {
                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
