/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PingGet$Params as PingGet$Params } from './fn/web-api/ping-get';
export { pingGet as pingGet } from './fn/web-api/ping-get';
export type { TravelsUploadPost$Params as TravelsUploadPost$Params } from './fn/travels/travels-upload-post';
export { travelsUploadPost as travelsUploadPost } from './fn/travels/travels-upload-post';
