/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderListDto {
  customerName: string;
  id: number;
  numberOfBracelets: number;
  orderDate: string;
  totalCosts: number;
}
