/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderItemDto } from '../models/order-item-dto';
export interface OrderDetailDto {
  customerAddress: string;
  customerName: string;
  id: number;
  orderDate: string;
  orderItems: Array<OrderItemDto>;
  totalCosts: number;
}
