/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AddItemRequestDto } from './models/add-item-request-dto';
export type { AddItemResponseDto } from './models/add-item-response-dto';
export type { AuthRequestDto } from './models/auth-request-dto';
export type { MarkAsBoughtRequestDto } from './models/mark-as-bought-request-dto';
export type { VerifyPinRequestDto } from './models/verify-pin-request-dto';
export type { VerifyPinResponseDto } from './models/verify-pin-response-dto';
export type { WishlistItemDto } from './models/wishlist-item-dto';
