/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PingGet$Params as PingGet$Params } from './fn/web-api/ping-get';
export { pingGet as pingGet } from './fn/web-api/ping-get';
export type { TravelsGet$Params as TravelsGet$Params } from './fn/travels/travels-get';
export { travelsGet as travelsGet } from './fn/travels/travels-get';
export type { TravelsIdGet$Params as TravelsIdGet$Params } from './fn/travels/travels-id-get';
export { travelsIdGet as travelsIdGet } from './fn/travels/travels-id-get';
export type { TravelsUploadPost$Params as TravelsUploadPost$Params } from './fn/travels/travels-upload-post';
export { travelsUploadPost as travelsUploadPost } from './fn/travels/travels-upload-post';
