/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddItemRequestDto } from '../../models/add-item-request-dto';
import { AddItemResponseDto } from '../../models/add-item-response-dto';

export interface WishlistNameItemsAddPost$Params {
  name: string;
      body: AddItemRequestDto
}

export function wishlistNameItemsAddPost(http: HttpClient, rootUrl: string, params: WishlistNameItemsAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AddItemResponseDto>> {
  const rb = new RequestBuilder(rootUrl, wishlistNameItemsAddPost.PATH, 'post');
  if (params) {
    rb.path('name', params.name, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AddItemResponseDto>;
    })
  );
}

wishlistNameItemsAddPost.PATH = '/wishlist/{name}/items/add';
