/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthRequestDto } from '../../models/auth-request-dto';
import { WishlistItemDto } from '../../models/wishlist-item-dto';

export interface WishlistNameItemsPost$Params {
  name: string;
      body: AuthRequestDto
}

export function wishlistNameItemsPost(http: HttpClient, rootUrl: string, params: WishlistNameItemsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WishlistItemDto>>> {
  const rb = new RequestBuilder(rootUrl, wishlistNameItemsPost.PATH, 'post');
  if (params) {
    rb.path('name', params.name, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WishlistItemDto>>;
    })
  );
}

wishlistNameItemsPost.PATH = '/wishlist/{name}/items';
