/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MarkAsBoughtRequestDto } from '../../models/mark-as-bought-request-dto';

export interface WishlistNameItemsItemIdMarkAsBoughtPost$Params {
  name: string;
  itemId: number;
      body: MarkAsBoughtRequestDto
}

export function wishlistNameItemsItemIdMarkAsBoughtPost(http: HttpClient, rootUrl: string, params: WishlistNameItemsItemIdMarkAsBoughtPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, wishlistNameItemsItemIdMarkAsBoughtPost.PATH, 'post');
  if (params) {
    rb.path('name', params.name, {});
    rb.path('itemId', params.itemId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

wishlistNameItemsItemIdMarkAsBoughtPost.PATH = '/wishlist/{name}/items/{itemId}/mark-as-bought';
