/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimeEntry } from '../models/time-entry';
export type Employee2 = ({
'id'?: number;
'emplyeeId'?: string;
'employeeName'?: string;
'timeEntries'?: Array<TimeEntry>;
}) | null;

