/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimeEntry } from '../models/time-entry';
export interface Project2 {
  id?: number;
  projectCode?: string;
  timeEntries?: Array<TimeEntry>;
}
