/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimeEntryUpdateDto {
  date: string;
  description: string;
  employeeId: number;
  endTime: string;
  projectId: number;
  startTime: string;
}
