/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimeEntryDto {
  date: string;
  description: string;
  employeeId: number;
  employeeName: string;
  endTime: string;
  id: number;
  projectCode: string;
  projectId: number;
  startTime: string;
}
