/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Employee2 } from '../models/employee-2';
import { Project } from '../models/project';
export interface TimeEntry {
  date?: string;
  description?: string;
  employee?: Employee2 | null;
  employeeId?: number;
  endTime?: string;
  id?: number;
  project?: Project | null;
  projectId?: number;
  startTime?: string;
}
