/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoriesGet$Params } from './fn/web-api/categories-get';
export { categoriesGet } from './fn/web-api/categories-get';
export type { ProductsGet$Params } from './fn/web-api/products-get';
export { productsGet } from './fn/web-api/products-get';
export type { ProductsIdGet$Params } from './fn/web-api/products-id-get';
export { productsIdGet } from './fn/web-api/products-id-get';
export type { ProductsIdPut$Params } from './fn/web-api/products-id-put';
export { productsIdPut } from './fn/web-api/products-id-put';
export type { ProductsIdDelete$Params } from './fn/web-api/products-id-delete';
export { productsIdDelete } from './fn/web-api/products-id-delete';
