/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerPatchDto {
  customerValue?: number | null;
  dateOfBirth?: string | null;
  isActive?: boolean | null;
  name?: string | null;
  revenue?: number | null;
}
