/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiPingGet$Params as ApiPingGet$Params } from './fn/web-api/api-ping-get';
export { apiPingGet as apiPingGet } from './fn/web-api/api-ping-get';
