/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PingGet$Params } from './fn/web-api/ping-get';
export { pingGet } from './fn/web-api/ping-get';
export type { DummiesGet$Params } from './fn/web-api/dummies-get';
export { dummiesGet } from './fn/web-api/dummies-get';
export type { DummyLogicPost$Params } from './fn/web-api/dummy-logic-post';
export { dummyLogicPost } from './fn/web-api/dummy-logic-post';
