/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PingGet$Params as PingGet$Params } from './fn/web-api/ping-get';
export { pingGet as pingGet } from './fn/web-api/ping-get';
export type { DummiesGet$Params as DummiesGet$Params } from './fn/web-api/dummies-get';
export { dummiesGet as dummiesGet } from './fn/web-api/dummies-get';
export type { DummyLogicPost$Params as DummyLogicPost$Params } from './fn/web-api/dummy-logic-post';
export { dummyLogicPost as dummyLogicPost } from './fn/web-api/dummy-logic-post';
export type { GeneratePost$Params as GeneratePost$Params } from './fn/demo-endpoints/generate-post';
export { generatePost as generatePost } from './fn/demo-endpoints/generate-post';
