/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { DemoInputDto } from './models/demo-input-dto';
export type { DemoOutputDto } from './models/demo-output-dto';
export type { Dummy } from './models/dummy';
