/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { LoginGet$Params as LoginGet$Params } from './fn/web-api/login-get';
export { loginGet as loginGet } from './fn/web-api/login-get';
export type { LogoutGet$Params as LogoutGet$Params } from './fn/web-api/logout-get';
export { logoutGet as logoutGet } from './fn/web-api/logout-get';
export type { MeGet$Params as MeGet$Params } from './fn/web-api/me-get';
export { meGet as meGet } from './fn/web-api/me-get';
export type { CustomersGet$Params as CustomersGet$Params } from './fn/web-api/customers-get';
export { customersGet as customersGet } from './fn/web-api/customers-get';
export type { CustomersPost$Params as CustomersPost$Params } from './fn/web-api/customers-post';
export { customersPost as customersPost } from './fn/web-api/customers-post';
export type { CustomersIdGet$Params as CustomersIdGet$Params } from './fn/web-api/customers-id-get';
export { customersIdGet as customersIdGet } from './fn/web-api/customers-id-get';
export type { CustomersIdPut$Params as CustomersIdPut$Params } from './fn/web-api/customers-id-put';
export { customersIdPut as customersIdPut } from './fn/web-api/customers-id-put';
export type { CustomersIdDelete$Params as CustomersIdDelete$Params } from './fn/web-api/customers-id-delete';
export { customersIdDelete as customersIdDelete } from './fn/web-api/customers-id-delete';
export type { SecretsGet$Params as SecretsGet$Params } from './fn/web-api/secrets-get';
export { secretsGet as secretsGet } from './fn/web-api/secrets-get';
export type { SecretsPost$Params as SecretsPost$Params } from './fn/web-api/secrets-post';
export { secretsPost as secretsPost } from './fn/web-api/secrets-post';
export type { SecretsIdGet$Params as SecretsIdGet$Params } from './fn/web-api/secrets-id-get';
export { secretsIdGet as secretsIdGet } from './fn/web-api/secrets-id-get';
export type { SecretsIdPut$Params as SecretsIdPut$Params } from './fn/web-api/secrets-id-put';
export { secretsIdPut as secretsIdPut } from './fn/web-api/secrets-id-put';
export type { SecretsIdDelete$Params as SecretsIdDelete$Params } from './fn/web-api/secrets-id-delete';
export { secretsIdDelete as secretsIdDelete } from './fn/web-api/secrets-id-delete';
export type { SecretsIdUpdateGet$Params as SecretsIdUpdateGet$Params } from './fn/web-api/secrets-id-update-get';
export { secretsIdUpdateGet as secretsIdUpdateGet } from './fn/web-api/secrets-id-update-get';
