/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CustomerCreateDto } from './models/customer-create-dto';
export type { CustomerDto } from './models/customer-dto';
export type { CustomerUpdateDto } from './models/customer-update-dto';
export type { SecretsCreateDto } from './models/secrets-create-dto';
export type { SecretsDto } from './models/secrets-dto';
export type { SecretsUpdateDto } from './models/secrets-update-dto';
