/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TravelReimbursementDto } from '../models/travel-reimbursement-dto';
export interface TravelDetailsDto {
  end: string;
  expenses: number;
  id: number;
  mileage: number;
  perDiem: number;
  purpose: string;
  reimbursements: Array<TravelReimbursementDto>;
  start: string;
  travelerName: string;
}
