/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Employee } from '../../models/employee';

export interface EmployeesGet$Params {
}

export function employeesGet(http: HttpClient, rootUrl: string, params?: EmployeesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Employee>>> {
  const rb = new RequestBuilder(rootUrl, employeesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Employee>>;
    })
  );
}

employeesGet.PATH = '/employees';
