/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Project2 } from '../../models/project-2';

export interface ProjectsGet$Params {
}

export function projectsGet(http: HttpClient, rootUrl: string, params?: ProjectsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Project2>>> {
  const rb = new RequestBuilder(rootUrl, projectsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Project2>>;
    })
  );
}

projectsGet.PATH = '/projects';
