/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PingResultDto } from '../../models/ping-result-dto';

export interface ApiPingGet$Params {
}

export function apiPingGet(http: HttpClient, rootUrl: string, params?: ApiPingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PingResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiPingGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PingResultDto>;
    })
  );
}

apiPingGet.PATH = '/api/ping';
