/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateOrderDto } from '../../models/create-order-dto';
import { OrderDetailDto } from '../../models/order-detail-dto';

export interface ApiOrdersPost$Params {
      body: CreateOrderDto
}

export function apiOrdersPost(http: HttpClient, rootUrl: string, params: ApiOrdersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiOrdersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderDetailDto>;
    })
  );
}

apiOrdersPost.PATH = '/api/orders';
