/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderDetailDto } from '../../models/order-detail-dto';

export interface ApiOrdersIdGet$Params {
  id: number;
}

export function apiOrdersIdGet(http: HttpClient, rootUrl: string, params: ApiOrdersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiOrdersIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderDetailDto>;
    })
  );
}

apiOrdersIdGet.PATH = '/api/orders/{id}';
