/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderListDto } from '../../models/order-list-dto';

export interface ApiOrdersGet$Params {
  minTotalCosts?: number;
}

export function apiOrdersGet(http: HttpClient, rootUrl: string, params?: ApiOrdersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiOrdersGet.PATH, 'get');
  if (params) {
    rb.query('minTotalCosts', params.minTotalCosts, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderListDto>>;
    })
  );
}

apiOrdersGet.PATH = '/api/orders';
