/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductUpdateDto {
  category: string | null;
  pricePerUnit: number;
  productCode: string;
  productDescription: string | null;
  productName: string;
}
