/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerDto } from '../../models/customer-dto';

export interface CustomersGet$Params {
}

export function customersGet(http: HttpClient, rootUrl: string, params?: CustomersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerDto>>> {
  const rb = new RequestBuilder(rootUrl, customersGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomerDto>>;
    })
  );
}

customersGet.PATH = '/customers';
