/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecretsDto } from '../../models/secrets-dto';

export interface SecretsIdUpdateGet$Params {
  id: number;
  connectionString: string;
}

export function secretsIdUpdateGet(http: HttpClient, rootUrl: string, params: SecretsIdUpdateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SecretsDto>> {
  const rb = new RequestBuilder(rootUrl, secretsIdUpdateGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('connectionString', params.connectionString, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SecretsDto>;
    })
  );
}

secretsIdUpdateGet.PATH = '/secrets/{id}/update';
