/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecretsDto } from '../../models/secrets-dto';

export interface SecretsGet$Params {
}

export function secretsGet(http: HttpClient, rootUrl: string, params?: SecretsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SecretsDto>>> {
  const rb = new RequestBuilder(rootUrl, secretsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SecretsDto>>;
    })
  );
}

secretsGet.PATH = '/secrets';
