/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecretsCreateDto } from '../../models/secrets-create-dto';
import { SecretsDto } from '../../models/secrets-dto';

export interface SecretsPost$Params {
      body: SecretsCreateDto
}

export function secretsPost(http: HttpClient, rootUrl: string, params: SecretsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SecretsDto>> {
  const rb = new RequestBuilder(rootUrl, secretsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SecretsDto>;
    })
  );
}

secretsPost.PATH = '/secrets';
