/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { EmployeesGet$Params } from './fn/web-api/employees-get';
export { employeesGet } from './fn/web-api/employees-get';
export type { ProjectsGet$Params } from './fn/web-api/projects-get';
export { projectsGet } from './fn/web-api/projects-get';
export type { TimeentriesGet$Params } from './fn/web-api/timeentries-get';
export { timeentriesGet } from './fn/web-api/timeentries-get';
export type { TimeentriesIdGet$Params } from './fn/web-api/timeentries-id-get';
export { timeentriesIdGet } from './fn/web-api/timeentries-id-get';
export type { TimeentriesIdPut$Params } from './fn/web-api/timeentries-id-put';
export { timeentriesIdPut } from './fn/web-api/timeentries-id-put';
export type { TimeentriesIdDelete$Params } from './fn/web-api/timeentries-id-delete';
export { timeentriesIdDelete } from './fn/web-api/timeentries-id-delete';
