/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Employee } from './models/employee';
export type { Employee2 } from './models/employee-2';
export type { Project } from './models/project';
export type { Project2 } from './models/project-2';
export type { TimeEntry } from './models/time-entry';
export type { TimeEntryDto } from './models/time-entry-dto';
export type { TimeEntryUpdateDto } from './models/time-entry-update-dto';
