/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelDetailsDto } from '../../models/travel-details-dto';

export interface TravelsIdGet$Params {
  id: number;
}

export function travelsIdGet(http: HttpClient, rootUrl: string, params: TravelsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TravelDetailsDto>> {
  const rb = new RequestBuilder(rootUrl, travelsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TravelDetailsDto>;
    })
  );
}

travelsIdGet.PATH = '/travels/{id}';
