/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TravelReimbursementDto {
  amount: number | null;
  description: string;
  id: number;
  km: number | null;
  type: string;
}
