/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PingGet$Params as PingGet$Params } from './fn/web-api/ping-get';
export { pingGet as pingGet } from './fn/web-api/ping-get';
export type { CustomersGet$Params as CustomersGet$Params } from './fn/web-api/customers-get';
export { customersGet as customersGet } from './fn/web-api/customers-get';
export type { CustomersPost$Params as CustomersPost$Params } from './fn/web-api/customers-post';
export { customersPost as customersPost } from './fn/web-api/customers-post';
export type { CustomersIdGet$Params as CustomersIdGet$Params } from './fn/web-api/customers-id-get';
export { customersIdGet as customersIdGet } from './fn/web-api/customers-id-get';
export type { CustomersIdDelete$Params as CustomersIdDelete$Params } from './fn/web-api/customers-id-delete';
export { customersIdDelete as customersIdDelete } from './fn/web-api/customers-id-delete';
export type { CustomersIdPatch$Params as CustomersIdPatch$Params } from './fn/web-api/customers-id-patch';
export { customersIdPatch as customersIdPatch } from './fn/web-api/customers-id-patch';
